config/routes.rb
Rails.application.routes.draw do
  root to: "weather_data#index"

  resources :weather_data
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather_datum.rb
class WeatherDatum < ApplicationRecord
  validates :zipcode, presence: true
  validate :presence_of_temperature_data

  private

  def presence_of_temperature_data
    return if temperature_c.present? || temperature_f.present?
    errors.add(:temperature, "must be present")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_data_controller.rb
require "net/http"

class WeatherDataController < ApplicationController
  before_action :set_weather_datum, only: [:show, :edit, :update, :destroy]

  def index
    @weather_data = WeatherDatum.all
  end

  def show
  end

  def new
    @weather_datum = WeatherDatum.new
  end

  def edit
  end

  def create
    @weather_datum = WeatherDatum.new(weather_datum_params)

    if @weather_datum.zipcode
      FetchWeatherData.call(zipcode: @weather_datum.zipcode)
    end

    if @weather_datum.zipcode
      uri = URI("http://api.openweathermap.org/data/2.5/weather")
      uri.query = URI.encode_www_form(zip: @weather_datum.zipcode, appid: ENV['WEATHER_API_KEY'])

      response = Net::HTTP.get_response(uri)
      if response.is_a?(Net::HTTPSuccess)
        json_response = JSON.parse(response.body)

        temperature_kelvin = json_response.dig("main", "temp")
        if temperature_kelvin
          @weather_datum.temperature_f = temperature_kelvin * 9/5 - 459.67
          @weather_datum.temperature_c = temperature_kelvin - 273.15
        end
      end
    end

    respond_to do |format|
      if @weather_datum.save
        format.html { redirect_to @weather_datum, notice: 'Weather data fetched.' }
        format.json { render :show, status: :created, location: @weather_datum }
      else
        format.html { render :new }
        format.json { render json: @weather_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @weather_datum.update(weather_datum_params)
        format.html { redirect_to @weather_datum, notice: 'Weather datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather_datum }
      else
        format.html { render :edit }
        format.json { render json: @weather_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @weather_datum.destroy
    respond_to do |format|
      format.html { redirect_to weather_data_url, notice: 'Weather datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_weather_datum
      @weather_datum = WeatherDatum.find(params[:id])
    end

    def weather_datum_params
      params.require(:weather_datum).permit(:zipcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_data_helper.rb
module WeatherDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FetchWeather</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather_data/_form.html.erb
<%= form_with(model: weather_datum, local: true) do |form| %>
  <% if weather_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather_datum.errors.count, "error") %> prohibited this weather_datum from being saved:</h2>

      <ul>
      <% weather_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, id: :weather_datum_zipcode %>
  </div>

  <div class="actions">
    <%= form.submit "Fetch weather data" %>
  </div>
<% end %>

app/views/weather_data/edit.html.erb
<h1>Editing Weather Datum</h1>

<%= render 'form', weather_datum: @weather_datum %>

<%= link_to 'Show', @weather_datum %> |
<%= link_to 'Back', weather_data_path %>

app/views/weather_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weather Data</h1>

<table>
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>Zipcode</th>
      <th>Temperature</th>
    </tr>
  </thead>

  <tbody>
    <% @weather_data.each do |weather_datum| %>
      <tr>
        <td><%= weather_datum.created_at %></td>
        <td><%= weather_datum.zipcode %></td>
        <td>
          <%= weather_datum.temperature_f %>F /
          <%= weather_datum.temperature_c %>C
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather Datum', new_weather_datum_path %>

app/views/weather_data/new.html.erb
<h1>Fetch weather</h1>

<%= render 'form', weather_datum: @weather_datum %>

<%= link_to 'Back', weather_data_path %>

app/views/weather_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zipcode:</strong>
  <%= @weather_datum.zipcode %>
</p>

<p>
  <strong>Temperature f:</strong>
  <%= @weather_datum.temperature_f %>
</p>

<p>
  <strong>Temperature c:</strong>
  <%= @weather_datum.temperature_c %>
</p>

<%= link_to 'Edit', edit_weather_datum_path(@weather_datum) %> |
<%= link_to 'Back', weather_data_path %>